import { useState } from 'react'
import { Plus, Trophy, Trash2, X } from 'lucide-react'
import AppIcon from './AppIcon.jsx'
import { formatCurrency, formatDate, parseAmount } from '../utils/format.js'

function AporteModal({ goal, onSave, onClose }) {
  const [amount, setAmount] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [busy, setBusy] = useState(false)
  const submit = async (e) => { e.preventDefault(); const value = parseAmount(amount); if (!value || !date) return; setBusy(true); const ok = await onSave(goal.id, { amount: value, occurredOn: date }); setBusy(false); if (ok) onClose() }
  return <div className="reverse-modal-backdrop" onMouseDown={onClose}><form className="reverse-details aporte-modal" onMouseDown={(e) => e.stopPropagation()} onSubmit={submit}><div className="row-between"><div className="card-title">Fazer aporte</div><button className="icon-btn" type="button" onClick={onClose}><X size={18} /></button></div><label className="label">Valor do aporte *</label><input className="input mono aporte-value" value={amount} onChange={(e) => setAmount(e.target.value)} inputMode="decimal" autoFocus required /><label className="label">Data real do aporte *</label><input className="input" type="date" min={goal.reverseStartDate} max={new Date().toISOString().slice(0, 10)} value={date} onChange={(e) => setDate(e.target.value)} required /><button className="btn btn-primary" disabled={busy}>{busy ? 'Salvando...' : 'Salvar aporte'}</button></form></div>
}

function Details({ goal, history, contributions, events, onClose }) {
  const rows = [...history.map((x) => ({ ...x, kind: 'correction', date: x.applied_on })), ...contributions.map((x) => ({ ...x, kind: 'contribution', date: x.occurred_on })), ...events.filter((x) => x.event_type !== 'contribution').map((x) => ({ ...x, kind: x.event_type, date: x.occurred_on }))].sort((a,b) => String(b.date).localeCompare(String(a.date)))
  return <div className="reverse-modal-backdrop" onMouseDown={onClose}><section className="reverse-details" onMouseDown={(e) => e.stopPropagation()}><div className="row-between"><div><div className="card-title">Mais detalhes</div><div className="card-sub">{goal.name}</div></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><div className="reverse-timeline">{rows.map((r,i) => r.kind==='correction' ? <article key={`h${i}`}><strong>{formatDate(r.date)} · Correção mensal</strong><p>+ {formatCurrency(Number(r.correction_amount))} adicionados ao cofrinho.</p></article> : r.kind==='contribution' ? <article key={`c${i}`}><strong>{formatDate(r.date)} · Aporte</strong><p>{formatCurrency(Number(r.amount))} recompostos.</p></article> : <article key={`e${i}`}><strong>{formatDate(r.date)} · {r.kind==='recalculated'?'Histórico recalculado':r.kind==='completed'?'Meta concluída':'Meta criada'}</strong><p>{r.details?.message || 'Movimentação registrada.'}</p></article>)}</div></section></div>
}

function ReverseCard({ goal, history, contributions, events, onAporte, onDelete }) {
 const [open,setOpen]=useState(false); const [aporte,setAporte]=useState(false); const [details,setDetails]=useState(false)
 return <div className="goal-card reverse-goal-card"><button className="reverse-card-main" onClick={()=>setOpen(!open)} aria-expanded={open}><span className="goal-icon" style={{background:`${goal.color}22`,color:goal.color}}><AppIcon emoji={goal.icon}/></span><span><strong>{goal.name}</strong><small>Meta Reversa</small></span></button><div className="progress"><div className="progress-bar" style={{width:`${goal.reverseProgressPercent}%`,background:goal.color}}/></div>{open&&<><div className="reverse-summary"><span>Valor original<strong>{formatCurrency(goal.reverseOriginalAmount)}</strong></span><span>Total aportado<strong>{formatCurrency(goal.reverseTotalContributed)}</strong></span><span>Correção acumulada<strong>{formatCurrency(goal.reverseCorrectionAmount)}</strong></span><span>Saldo restante<strong>{formatCurrency(goal.reverseRemainingAmount)}</strong></span><span>Progresso<strong>{Number(goal.reverseProgressPercent).toFixed(0)}%</strong></span></div>{goal.reverseRemainingAmount>0&&<button className="btn btn-primary" onClick={()=>setAporte(true)}>Fazer aporte</button>}<div className="row" style={{marginTop:12}}><button className="btn btn-sm" onClick={()=>setDetails(true)}>Mais detalhes</button><button className="icon-btn danger" onClick={()=>onDelete(goal.id)}><Trash2 size={15}/></button></div></>}{aporte&&<AporteModal goal={goal} onSave={onAporte} onClose={()=>setAporte(false)}/>} {details&&<Details goal={goal} history={history} contributions={contributions} events={events} onClose={()=>setDetails(false)}/>}</div>
}

export default function GoalsPanel({ goals, reverseHistory, reverseContributions, reverseEvents, onAddReverse, onAddReverseContribution, onDelete }) {
 const [form,setForm]=useState(false); const [name,setName]=useState(''); const [value,setValue]=useState(''); const [start,setStart]=useState(new Date().toISOString().slice(0,10))
 const create=async(e)=>{e.preventDefault();const ok=await onAddReverse({name,originalAmount:parseAmount(value),initialContribution:0,startDate:start,selicFactor:1,icon:'🎯',color:'#6366f1'});if(ok){setForm(false);setName('');setValue('')}}
 return <div className="stack"><div className="card"><div className="card-head"><div><div className="card-title">Metas de economia</div><div className="card-sub">Metas comuns e Metas Reversas</div></div><button className="btn btn-primary btn-sm" onClick={()=>setForm(!form)}><Plus size={15}/> Nova Meta Reversa</button></div></div>{form&&<form className="card form-grid" onSubmit={create}><div className="field"><label className="label">Nome *</label><input className="input" value={name} onChange={e=>setName(e.target.value)} required/></div><div className="field"><label className="label">Valor inicial *</label><input className="input mono" value={value} onChange={e=>setValue(e.target.value)} required/></div><div className="field"><label className="label">Data de início *</label><input className="input" type="date" value={start} onChange={e=>setStart(e.target.value)} required/></div><button className="btn btn-primary">Criar meta</button></form>}{goals.length?<div className="grid-3">{goals.map(g=>g.goalType==='reverse'?<ReverseCard key={g.id} goal={g} history={reverseHistory.filter(x=>x.goal_id===g.id)} contributions={reverseContributions.filter(x=>x.goal_id===g.id)} events={reverseEvents.filter(x=>x.goal_id===g.id)} onAporte={onAddReverseContribution} onDelete={onDelete}/>:<div className="goal-card" key={g.id}><strong>{g.name}</strong><div className="progress"><div className="progress-bar" style={{width:`${g.target?g.current/g.target*100:0}%`,background:g.color}}/></div></div>)}</div>:<div className="card empty"><Trophy/><div>Nenhuma meta cadastrada</div></div>}</div>
}
