import { useState } from 'react'
import { CircleHelp, Pencil, Plus, Trash2, Trophy, X } from 'lucide-react'
import AppIcon from './AppIcon.jsx'
import { formatCurrency, formatDate, formatPercent, parseAmount } from '../utils/format.js'

const ICONS = ['🎯', '✈️', '🏠', '🚗', '💻', '🎓', '💍', '🏖️', '📱', '🎁']
const COLORS = ['#6366f1', '#22c55e', '#0ea5e9', '#f97316', '#ec4899', '#8b5cf6']

function GoalForm({ initial, onSave, onCancel }) {
  const [reverse, setReverse] = useState(initial?.goalType === 'reverse'); const [busy, setBusy] = useState(false)
  const [f,setF]=useState(initial||{name:'',target:'',current:'',deadline:'',icon:'🎯',color:'#6366f1',originalAmount:'',initialContribution:'',startDate:new Date().toISOString().slice(0,10),selicFactor:1})
  const set=(p)=>setF(v=>({...v,...p})); const submit=async(e)=>{e.preventDefault();const data=reverse?{...f,goalType:'reverse',originalAmount:parseAmount(f.originalAmount),initialContribution:parseAmount(f.initialContribution),selicFactor:Number(f.selicFactor)||1}:{...f,goalType:'standard',target:parseAmount(f.target),current:parseAmount(f.current)};if(!data.name.trim()||(reverse?!data.originalAmount||!data.startDate:!data.target))return;setBusy(true);const ok=await onSave(data);setBusy(false);if(ok!==false)onCancel()}
  return <form className="card" onSubmit={submit}><div className="row-between"><div><strong>Esta meta é Reversa?</strong><div className="text-xs text-muted">Recomposição corrigida pela Selic.</div></div><button type="button" className={`goal-switch${reverse?' active':''}`} onClick={()=>setReverse(!reverse)} role="switch" aria-checked={reverse}><span/></button></div>{reverse&&<details className="reverse-help" open><summary><CircleHelp size={16}/> Como funciona?</summary><p>O saldo restante é corrigido pela Selic até chegar a zero.</p></details>}<div className="form-grid" style={{marginTop:16}}><div className="field span-2"><label className="label">Nome *</label><input className="input" value={f.name} onChange={e=>set({name:e.target.value})} required/></div>{reverse?<><div className="field"><label className="label">Valor inicial *</label><input className="input mono" value={f.originalAmount} onChange={e=>set({originalAmount:e.target.value})} inputMode="decimal"/></div><div className="field"><label className="label">Já recomposto</label><input className="input mono" value={f.initialContribution} onChange={e=>set({initialContribution:e.target.value})} inputMode="decimal"/></div><div className="field"><label className="label">Data de início *</label><input className="input" type="date" value={f.startDate} max={new Date().toISOString().slice(0,10)} onChange={e=>set({startDate:e.target.value})}/></div><div className="field"><label className="label">Fator Selic</label><input className="input" type="number" min="0.5" max="1.5" step="0.005" value={f.selicFactor} onChange={e=>set({selicFactor:e.target.value})}/></div></>:<><div className="field"><label className="label">Valor alvo *</label><input className="input mono" value={f.target} onChange={e=>set({target:e.target.value})} inputMode="decimal"/></div><div className="field"><label className="label">Já guardado</label><input className="input mono" value={f.current} onChange={e=>set({current:e.target.value})} inputMode="decimal"/></div><div className="field"><label className="label">Prazo</label><input className="input" type="date" value={f.deadline} onChange={e=>set({deadline:e.target.value})}/></div></>}<div className="field span-2"><label className="label">Ícone e cor</label><div className="swatch-grid">{ICONS.map(i=><button type="button" className={`swatch${f.icon===i?' selected':''}`} onClick={()=>set({icon:i})} key={i}><AppIcon emoji={i}/></button>)}</div><div className="swatch-grid">{COLORS.map(c=><button type="button" className={`color-dot${f.color===c?' selected':''}`} onClick={()=>set({color:c})} style={{background:c}} key={c}/>)}</div></div></div><div className="row" style={{justifyContent:'flex-end',marginTop:16}}><button className="btn" type="button" onClick={onCancel}>Cancelar</button><button className="btn btn-primary" disabled={busy}>{busy?'Salvando...':'Salvar meta'}</button></div></form>
}

function AporteModal({goal,onSave,onClose}){const[a,setA]=useState(''),[d,setD]=useState(new Date().toISOString().slice(0,10));const submit=async e=>{e.preventDefault();if(await onSave(goal.id,{amount:parseAmount(a),occurredOn:d}))onClose()};return <div className="reverse-modal-backdrop" onMouseDown={onClose}><form className="reverse-details aporte-modal" onMouseDown={e=>e.stopPropagation()} onSubmit={submit}><div className="row-between"><strong>Fazer aporte</strong><button type="button" className="icon-btn" onClick={onClose}><X size={18}/></button></div><label className="label">Valor *</label><input className="input mono aporte-value" value={a} onChange={e=>setA(e.target.value)} required autoFocus/><label className="label">Data real *</label><input className="input" type="date" min={goal.reverseStartDate} max={new Date().toISOString().slice(0,10)} value={d} onChange={e=>setD(e.target.value)} required/><button className="btn btn-primary">Salvar aporte</button></form></div>}

function ReverseCard({goal,onAporte,onDelete}){const[open,setOpen]=useState(false),[modal,setModal]=useState(false);return <div className="goal-card reverse-goal-card"><button className="reverse-card-main" onClick={()=>setOpen(!open)}><span className="goal-icon" style={{background:`${goal.color}22`,color:goal.color}}><AppIcon emoji={goal.icon}/></span><span><strong>{goal.name}</strong><small>Meta Reversa</small></span></button><div className="progress"><div className="progress-bar" style={{width:`${goal.reverseProgressPercent}%`,background:goal.color}}/></div>{open&&<><div className="reverse-summary"><span>Original<strong>{formatCurrency(goal.reverseOriginalAmount)}</strong></span><span>Aportado<strong>{formatCurrency(goal.reverseTotalContributed)}</strong></span><span>Correção<strong>{formatCurrency(goal.reverseCorrectionAmount)}</strong></span><span>Restante<strong>{formatCurrency(goal.reverseRemainingAmount)}</strong></span></div>{goal.reverseRemainingAmount>0&&<button className="btn btn-primary" onClick={()=>setModal(true)}>Fazer aporte</button>}<button className="icon-btn danger" onClick={()=>onDelete(goal.id)}><Trash2 size={15}/></button></>}{modal&&<AporteModal goal={goal} onSave={onAporte} onClose={()=>setModal(false)}/>}</div>}

function StandardCard({goal,onUpdate,onEdit,onDelete}){const[a,setA]=useState(''),p=goal.target?goal.current/goal.target*100:0;return <div className="goal-card"><div className="row-between"><div className="row"><div className="goal-icon" style={{background:`${goal.color}22`,color:goal.color}}><AppIcon emoji={goal.icon}/></div><strong>{goal.name}</strong></div><div className="row"><button className="icon-btn" onClick={()=>onEdit(goal)}><Pencil size={15}/></button><button className="icon-btn danger" onClick={()=>onDelete(goal.id)}><Trash2 size={15}/></button></div></div><div className="progress"><div className="progress-bar" style={{width:`${Math.min(100,p)}%`,background:goal.color}}/></div><div className="text-xs">{formatPercent(p,1)} concluído</div><form className="row" onSubmit={e=>{e.preventDefault();const v=parseAmount(a);if(v){onUpdate(goal.id,{current:goal.current+v});setA('')}}}><input className="input mono grow" value={a} onChange={e=>setA(e.target.value)} placeholder="Aportar R$..."/><button className="btn btn-primary btn-sm"><Plus size={15}/>Aportar</button></form></div>}

export default function GoalsPanel({goals,onAdd,onAddReverse,onAddReverseContribution,onUpdate,onDelete}){const[show,setShow]=useState(false),[editing,setEditing]=useState(null);const save=d=>d.goalType==='reverse'?onAddReverse(d):(editing?onUpdate(editing.id,d):onAdd(d));return <div className="stack"><div className="card row-between"><div><div className="card-title">Metas de economia</div><div className="card-sub">Crie metas normais ou reversas</div></div><button className="btn btn-primary" onClick={()=>{setEditing(null);setShow(true)}}><Plus size={15}/>Nova meta</button></div>{show&&<GoalForm initial={editing?{...editing,target:String(editing.target),current:String(editing.current)}:null} onSave={save} onCancel={()=>{setShow(false);setEditing(null)}}/>}{goals.length?<div className="grid-3">{goals.map(g=>g.goalType==='reverse'?<ReverseCard key={g.id} goal={g} onAporte={onAddReverseContribution} onDelete={onDelete}/>:<StandardCard key={g.id} goal={g} onUpdate={onUpdate} onEdit={g=>{setEditing(g);setShow(true)}} onDelete={onDelete}/>)}</div>:!show&&<div className="card empty"><Trophy/>Nenhuma meta cadastrada</div>}</div>}
